name: Manuel Trigger Example
on:
  workflow_dispatch:
    inputs:
      selected_value:
        description: 'Select a value'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up the repository
        uses: actions/checkout@v2

      - name: Get command output
        id: command_output
        run: echo "::set-output name=value::value1,value2,value3"

      - name: Print input value
        run: |
          selected=$1
          echo "Selected Value: $selected"
        shell: bash
        env:
          1: ${{ steps.command_output.outputs.value }}
