name: Manuel Trigger Example
on:
  workflow_dispatch:
    inputs:
      selected_value:
        description: 'Select a value'
        required: true
        default: 'value1'
        options: ${{ steps.get_options.outputs.oguz }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up the repository
        uses: actions/checkout@v2

      - name: Get options
        id: get_options
        run: |
          echo "::set-output name=oguz::$(echo 'value1, value2, value3')"

      - name: Check input
        if: ${{ !contains(steps.get_options.outputs.oguz, github.event.inputs.selected_value) }}
        run: echo "Invalid option selected. Please select a valid option." && exit 1

      - name: Print input value
        if: success()
        run: |
          selected=$1
          echo "Selected Value: $selected"
        shell: bash
        env:
          1: ${{ github.event.inputs.selected_value }}
