name: Manuel Trigger Example
on:
  workflow_dispatch:
    inputs:
      selected_value:
        description: 'Select a value'
        required: true
        default: 'value1'
        options: ['value1', 'value2', 'value3']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up the repository
        uses: actions/checkout@v2

      - name: Print input value
        run: |
          selected=$1
          echo "Selected Value: $selected"
        shell: bash
        env:
          1: ${{ github.event.inputs.selected_value }}
